Fix json deserialization error in ember 1.13
To reproduce, create an unclosed component in a template:

	<x-component>

This is the error:

	spray.json.DeserializationException: Expected Int as JsNumber, but got null